# Generated by Django 6.0.7 on 2026-08-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Qualification', models.CharField(max_length=15)),
                ('Specialization', models.CharField(max_length=50)),
                ('Experience', models.IntegerField()),
                ('Phone_number', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(max_length=10)),
                ('Birth_date', models.DateField()),
                ('Address', models.CharField(max_length=100)),
                ('consultation_Fee', models.CharField(max_length=10)),
                ('Department', models.CharField(max_length=20)),
                ('License', models.CharField(max_length=50)),
                ('Avalable_days', models.CharField(max_length=100)),
                ('joining_Date', models.DateField()),
            ],
        ),
    ]
